### ISSUE TITLE
Playing the game

### ISSUE THREAD

**Issue by tejank10** [Evizero/GoGame.jl#1]
I plan to use this repo to build the AlphaGo demo in Flux. How do I run the game?

**Comment by Evizero** [comment]
using `placestone` (see tests). Note though that one major thing is still not implemented, which is ending the game and deciding the winner

**Comment by tejank10** [comment]
I am interested in developing for the un-implemented part of the game so that we can get it to a playable state. Will it be possible for you to guide me during next few days in doing so?

**Comment by Evizero** [comment]
I can do that to an extend as time allows. Be warned though that I suspect this task could be quite challenging to pull off. Have you entertained the idea of using an existing Go implementation (e.g. OpenAI Gym)? Might save you some time on the game part and allow you to focus more on the reinforcement learning part.

**Comment by tejank10** [comment]
Thanks for the suggestion, I didn't know about it. I tried it, works pretty well. As of now, I'll use it.
